import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatStepperModule } from '@angular/material/stepper';
// import {MatDatepickerModule} from '@angular/material/datepicker';
// import { FlexLayoutModule } from '@angular/flex-layout';
import {
  MatButtonModule,
  MatMenuModule,
  MatToolbarModule,
  MatIconModule,
  MatCardModule,
  MatSelectModule,
  MatRadioModule,
  MatInputModule,
  MatFormFieldModule,
  MatTooltipModule,
  MatDialogModule,
  MatButtonToggleModule,
  MatTableModule,
  MatChipsModule,
  MatAutocompleteModule,
  MatPaginatorModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatCheckboxModule,
  MatSortModule,
  MatExpansionModule,
  MatProgressSpinnerModule,
  MatTabsModule,
  MatSidenavModule,
  MatListModule,
  MatOptionModule, MatGridListModule, MatProgressBarModule,
  MatSliderModule, MatSlideToggleModule, MatSnackBarModule,
  MatCommonModule,
  MatRippleModule,

} from '@angular/material';

@NgModule({
  declarations: [],
  imports: [
    // FlexLayoutModule,
    CommonModule,
    MatButtonModule,
    MatSelectModule,
    MatIconModule,
    MatButtonModule,
    MatMenuModule,
    MatToolbarModule,
    MatIconModule,
    MatCardModule,
    MatSelectModule,
    MatRadioModule,
    MatInputModule,
    MatFormFieldModule,
    MatTooltipModule,
    MatDialogModule,
    MatButtonToggleModule,
    MatTableModule,
    MatChipsModule,
    MatAutocompleteModule,
    MatPaginatorModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatCheckboxModule,
    MatSortModule,
    MatExpansionModule,
    MatProgressSpinnerModule,
    MatTabsModule,
    MatSidenavModule,
    MatListModule,
    MatOptionModule, MatGridListModule, MatProgressBarModule,
    MatSliderModule, MatSlideToggleModule, MatSnackBarModule,
    MatStepperModule,
    MatCommonModule,
    MatRippleModule,
  ],
  exports: [
    // FlexLayoutModule,
    CommonModule,
    MatButtonModule,
    MatSelectModule,
    MatIconModule,
    MatButtonModule,
    MatMenuModule,
    MatToolbarModule,
    MatIconModule,
    MatCardModule,
    MatSelectModule,
    MatRadioModule,
    MatInputModule,
    MatFormFieldModule,
    MatTooltipModule,
    MatDialogModule,
    MatButtonToggleModule,
    MatTableModule,
    MatChipsModule,
    MatAutocompleteModule,
    MatPaginatorModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatCheckboxModule,
    MatSortModule,
    MatExpansionModule,
    MatProgressSpinnerModule,
    MatTabsModule,
    MatSidenavModule,
    MatListModule,
    MatOptionModule, MatGridListModule, MatProgressBarModule,
    MatSliderModule, MatSlideToggleModule, MatSnackBarModule,
    MatStepperModule,
    MatCommonModule,
    MatRippleModule,
  ],
  schemas: [
    CUSTOM_ELEMENTS_SCHEMA,
  ],
})

export class MaterialModule { }
